name: Unit testing

on:
  pull_request:
   branches: [ main ]
  push: 
   branches: [ main ] 

jobs:
  build:
  
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        uses: webbertakken/unity-test-runner@v1.3
        with:
          projectPath: 3_Implementation
          unityVersion: 2019.2.11f1
