name: Unit testing

on:
  pull_request:
   branches: [ main ]
  push: 
   branches: [ main ] 

jobs:
  build:
  
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Install Unity
        run: sudo apt-get -y install libunity libunity-doc libunity_internals-doc
      - name: make test
        run: make test -C 3_Implementation 
