name: Valgrind

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: apt install dependency
      run: |
        sudo apt-get -y install valgrind
        sudo apt-get install unity
    - name: make 
      run: |
        make -C 3_Implementation
        valgrind ./3_Implementation/build/Test_MEDICALSTOREMANAGEMENTSYSTEM.out
